-- Allow explicit id inserts so _save_batch can bulk-insert with pre-fetched ids.
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE aryx_entity MODIFY id GENERATED BY DEFAULT AS IDENTITY';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
