-- MCP sales-scope columns. Shay-backed sales chat remains PostgreSQL-only.

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE aryx_mcp_token ADD (
    purpose VARCHAR2(100) DEFAULT ''general'' NOT NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE aryx_mcp_token ADD (
    allowed_tools VARCHAR2(4000) DEFAULT '' '' NOT NULL
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE aryx_mcp_token ADD (workspace_id NUMBER)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE aryx_mcp_token ADD (
    shay_workspace_id VARCHAR2(100)
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE aryx_mcp_token ADD (
    expires_at TIMESTAMP WITH TIME ZONE
  )';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1430 THEN RAISE; END IF;
END;
/
