"""Create gg_vault table

Revision ID: 001
Revises: 
Create Date: 2025-08-06 15:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gg_vault',
    sa.Column('giggso_vault_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('vault_label', sa.String(length=50), nullable=True),
    sa.Column('vault_unique_id', sa.String(length=50), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('vault_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('giggso_vault_id')
    )
    op.create_index('idx_vault_company_id', 'gg_vault', ['company_id'], unique=False)
    op.create_index('idx_vault_created_datetime', 'gg_vault', ['created_datetime'], unique=False)
    op.create_index('idx_vault_resource_id', 'gg_vault', ['resource_id'], unique=False)
    op.create_index('idx_vault_type', 'gg_vault', ['vault_type'], unique=False)
    op.create_index('idx_vault_unique_id', 'gg_vault', ['vault_unique_id'], unique=True)
    op.create_index(op.f('ix_gg_vault_company_id'), 'gg_vault', ['company_id'], unique=False)
    op.create_index(op.f('ix_gg_vault_resource_id'), 'gg_vault', ['resource_id'], unique=False)
    op.create_index(op.f('ix_gg_vault_vault_type'), 'gg_vault', ['vault_type'], unique=False)
    op.create_index(op.f('ix_gg_vault_vault_unique_id'), 'gg_vault', ['vault_unique_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gg_vault_vault_unique_id'), table_name='gg_vault')
    op.drop_index(op.f('ix_gg_vault_vault_type'), table_name='gg_vault')
    op.drop_index(op.f('ix_gg_vault_resource_id'), table_name='gg_vault')
    op.drop_index(op.f('ix_gg_vault_company_id'), table_name='gg_vault')
    op.drop_index('idx_vault_unique_id', table_name='gg_vault')
    op.drop_index('idx_vault_type', table_name='gg_vault')
    op.drop_index('idx_vault_resource_id', table_name='gg_vault')
    op.drop_index('idx_vault_created_datetime', table_name='gg_vault')
    op.drop_index('idx_vault_company_id', table_name='gg_vault')
    op.drop_table('gg_vault')
    # ### end Alembic commands ###


